In [2]:
import pandas as pd

In [7]:
df = pd.read_csv(r'C:\Users\lj\Desktop\IMDB Project\imdb sql cleaned file.csv')

In [6]:
df

,movie_rank,movie_name,release_year,release_season,duration,imdb_rate,vote_count,genre1,genre2,genre3,country,language_,box_office,age_group_rate
0,1,The Shawshank Redemption,1994,autumn,2h 22m,9.3,3.1m,epic,drama,prison drama,US,english,28784937,R
1,2,The Godfather,1972,spring,2h 55m,9.2,2.2m,crime,tragedy,drama,US,english-italian,250342198,R
2,3,The Dark Knight,2008,summer,2h 32m,9.1,3.1m,epic,action,superhero,US,english,1009057329,PG-13
3,4,The Godfather Part II,1974,winter,3h 22m,9.0,1.4m,tragedy,crime,drama,US,english-italian,88000000,R
4,5,12 Angry Men,1957,spring,1h 36m,9.0,946k,drama,crime,psychological,US,english,2945,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,246,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,2020,autumn,1h 57m,8.2,89k,superhero,adventure,animation,japan,japanese,486451200,TV-MA
245,247,The Help,2011,summer,2h 26m,8.1,519k,period drama,drama,drama,US,english,221802186,Not Rated
246,248,Gangs of Wasseypur,2012,summer,5h 21m,8.2,110k,thriller,drama,crime,india,hindi,4384642,PG-13
247,249,Drishyam,2015,summer,2h 43m,8.2,104k,mystry,drama,thriller,india,hindi,1800000,PG
248,250,Groundhog Day,1993,winter,1h 41m,8.0,725k,romance,drama,comedy,US,english,71108778,Not Rated

converting vote counts from numbers with 'K' and 'M' suffixes which imply to thousand and milliom to numerical values with those number units.
for instance :
3.1m, which is three million and one hundered thousand, is converted to 3100000
89k, which is eighty nine thousand, is converted to 89000

In [9]:
to_modify = df['vote_count']
for index, row in to_modify.items():
    if 'm' in row:
        to_modify.loc[index] = int(float(to_modify.loc[index].split('m')[0]) * 1000000)
    elif 'k' in row:
        to_modify.loc[index] = int(float(to_modify.loc[index].split('k')[0]) * 1000)
df['vote_count'] = to_modify

In [118]:
df['vote_count'] = df['vote_count'].astype(int)

In [9]:
df

,movie_rank,movie_name,release_year,release_season,duration,imdb_rate,vote_count,genre1,genre2,genre3,country,language_,box_office,age_group_rate
0,1,The Shawshank Redemption,1994,autumn,2h 22m,9.3,3100000,epic,drama,prison drama,US,english,28784937,R
1,2,The Godfather,1972,spring,2h 55m,9.2,2200000,crime,tragedy,drama,US,english-italian,250342198,R
2,3,The Dark Knight,2008,summer,2h 32m,9.1,3100000,epic,action,superhero,US,english,1009057329,PG-13
3,4,The Godfather Part II,1974,winter,3h 22m,9.0,1400000,tragedy,crime,drama,US,english-italian,88000000,R
4,5,12 Angry Men,1957,spring,1h 36m,9.0,946000,drama,crime,psychological,US,english,2945,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,246,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,2020,autumn,1h 57m,8.2,89000,superhero,adventure,animation,japan,japanese,486451200,TV-MA
245,247,The Help,2011,summer,2h 26m,8.1,519000,period drama,drama,drama,US,english,221802186,Not Rated
246,248,Gangs of Wasseypur,2012,summer,5h 21m,8.2,110000,thriller,drama,crime,india,hindi,4384642,PG-13
247,249,Drishyam,2015,summer,2h 43m,8.2,104000,mystry,drama,thriller,india,hindi,1800000,PG
248,250,Groundhog Day,1993,winter,1h 41m,8.0,725000,romance,drama,comedy,US,english,71108778,Not Rated

then here, 
values in duration column with hours and minutes all together will be converted to minutes
for instance :
2h 22m, which is two hours and 22 minutes will become 122 minutes.
the ones that are only minutes will remain the same, 
for instance :
48m, will remain 48 but the only change is that it's just gonna change to a numeric value, which is 48

In [10]:
edition = df['duration']
for index, row in edition.items():
    if 'm' in row and 'h' in row:
        x1 = edition.loc[index].split(r'h')
        x2 = int(x1[1].split('m')[0]) + int(x1[0])*60
        edition.loc[index] = x2
    elif 'h' in row and 'm' not in row:
        edition.loc[index] = int(edition.loc[index].split(r'h')[0]) * 60
    elif 'm' in row and 'h' not in row:
        edition.loc[index] = int(edition.loc[index].split(r'm')[0])
df['duration'] = edition

C:\Users\lj\AppData\Local\Temp/ipykernel_3468/205146728.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edition.loc[index] = x2
C:\Users\lj\AppData\Local\Temp/ipykernel_3468/205146728.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edition.loc[index] = int(edition.loc[index].split(r'h')[0]) * 60
C:\Users\lj\AppData\Local\Temp/ipykernel_3468/205146728.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edition.loc[index] = int(edition.loc[index].split(r'm')[0])

In [11]:
df['duration'] = df['duration'].astype(int)

In [12]:
df.rename(columns={'duration':'duration_in_minute'}, inplace=True)

In [13]:
df

,movie_rank,movie_name,release_year,release_season,duration_in_minute,imdb_rate,vote_count,genre1,genre2,genre3,country,language_,box_office,age_group_rate
0,1,The Shawshank Redemption,1994,autumn,142,9.3,3100000,epic,drama,prison drama,US,english,28784937,R
1,2,The Godfather,1972,spring,175,9.2,2200000,crime,tragedy,drama,US,english-italian,250342198,R
2,3,The Dark Knight,2008,summer,152,9.1,3100000,epic,action,superhero,US,english,1009057329,PG-13
3,4,The Godfather Part II,1974,winter,202,9.0,1400000,tragedy,crime,drama,US,english-italian,88000000,R
4,5,12 Angry Men,1957,spring,96,9.0,946000,drama,crime,psychological,US,english,2945,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,246,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,2020,autumn,117,8.2,89000,superhero,adventure,animation,japan,japanese,486451200,TV-MA
245,247,The Help,2011,summer,146,8.1,519000,period drama,drama,drama,US,english,221802186,Not Rated
246,248,Gangs of Wasseypur,2012,summer,321,8.2,110000,thriller,drama,crime,india,hindi,4384642,PG-13
247,249,Drishyam,2015,summer,163,8.2,104000,mystry,drama,thriller,india,hindi,1800000,PG
248,250,Groundhog Day,1993,winter,101,8.0,725000,romance,drama,comedy,US,english,71108778,Not Rated

In [16]:
df.dtypes

movie_rank              int64
movie_name             object
release_year            int64
release_season         object
duration_in_minute      int32
imdb_rate             float64
vote_count              int64
genre1                 object
genre2                 object
genre3                 object
country                object
language_              object
box_office              int64
age_group_rate         object
dtype: object

In [10]:
df.describe()

,movie_rank,release_year,duration_in_minute,imdb_rate,vote_count,box_office
count,249.000000,249.000000,249.000000,249.000000,2.490000e+02,2.490000e+02
mean,125.706827,1988.124498,130.859438,8.308434,7.383574e+05,2.153001e+08
std,72.384491,25.368028,35.961453,0.232901,5.935242e+05,3.305579e+08
min,1.000000,1921.000000,45.000000,8.000000,2.600000e+04,0.000000e+00
25%,63.000000,1972.000000,108.000000,8.100000,2.450000e+05,5.435312e+06
50%,126.000000,1995.000000,127.000000,8.200000,6.100000e+05,5.667673e+07
75%,188.000000,2008.000000,147.000000,8.400000,1.100000e+06,3.167913e+08
max,250.000000,2024.000000,374.000000,9.300000,3.100000e+06,2.052415e+09

In [11]:
df.corr()

,movie_rank,release_year,duration_in_minute,imdb_rate,vote_count,box_office
movie_rank,1.000000,-0.008180,-0.141440,-0.853019,-0.555185,-0.188052
release_year,-0.008180,1.000000,0.123298,0.040156,0.365916,0.419310
duration_in_minute,-0.141440,0.123298,1.000000,0.251741,0.105392,0.075018
imdb_rate,-0.853019,0.040156,0.251741,1.000000,0.588123,0.180866
vote_count,-0.555185,0.365916,0.105392,0.588123,1.000000,0.517380
box_office,-0.188052,0.419310,0.075018,0.180866,0.517380,1.000000

removing outliers, just for       release year    and    imdb rate

we don't remove outliers in the duration column, vote count and box office
because it is not reasonable to do it. if a movie is 10 hours long it's not an outlier because it's just longer than the rest, though, the formula will detect it as an outlier, but removing that case will just cause Data Loss.
even it box office, a movie sales can grow significantly high while the others can't or don't. if the formula detects it as an outlier, we don't remove that Data because it's just a movie that was much much more successful than the rest !!

In the cases of release year & imdb rate it is totally different.
because if we have a value that is minus 2 (-2) or a movie with 11 out of 10 rate (11/10),
these values are definitely outliers because they exceed the solid limits, 11 out of 10 is reasonable here, so it is an absolute outlier
Or
a movie with release year like 1600 or 2080 is also an outlier
because there was no camera in 1600 to record a movie or the year 2080 has not arrived yet !!
so these values are also considered as outliers

In [8]:
q1 = df.release_year.quantile(0.25)
q3 = df.release_year.quantile(0.75)
iqr = q3 - q1
lower_limit = q1 - 1.5*iqr
upper_limit = q3 + 1.5*iqr
df[(df.release_year<lower_limit)|(df.release_year>upper_limit)]

Empty DataFrame
Columns: [movie_rank, movie_name, release_year, release_season, duration_in_minute, imdb_rate, vote_count, genre1, genre2, genre3, country, language_, box_office, age_group_rate]
Index: []

here, the formula detects a few movies with imdb rates around 8.9 to 9.3 as outliers,
as you see they are not outliers, they're just a few movies that are more successful than the rest !!

In [9]:
q1 = df.imdb_rate.quantile(0.25)
q3 = df.imdb_rate.quantile(0.75)
iqr = q3 - q1
lower_limit = q1 - 1.5*iqr
upper_limit = q3 + 1.5*iqr
df[(df.imdb_rate<lower_limit)|(df.imdb_rate>upper_limit)]

,movie_rank,movie_name,release_year,release_season,duration_in_minute,imdb_rate,vote_count,genre1,genre2,genre3,country,language_,box_office,age_group_rate
0,1,The Shawshank Redemption,1994,autumn,142,9.3,3100000,epic,drama,prison drama,US,english,28784937,R
1,2,The Godfather,1972,spring,175,9.2,2200000,crime,tragedy,drama,US,english-italian,250342198,R
2,3,The Dark Knight,2008,summer,152,9.1,3100000,epic,action,superhero,US,english,1009057329,PG-13
3,4,The Godfather Part II,1974,winter,202,9.0,1400000,tragedy,crime,drama,US,english-italian,88000000,R
4,5,12 Angry Men,1957,spring,96,9.0,946000,drama,crime,psychological,US,english,2945,Approved
5,6,The Lord of the Rings: The Return of the King,2003,winter,201,9.0,2100000,epic,drama,quest,US,english,1118000000,PG-13
6,7,Schindler's List,1993,winter,195,9.0,1500000,history,drama,tragedy,US,english,322161245,R
8,9,The Lord of the Rings: The Fellowship of the Ring,2001,winter,178,8.9,2100000,epic,drama,quest,US,english,868000000,PG-13